import "./globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

// Definisikan font Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Pilih bobot yang kamu pakai
  variable: "--font-poppins", // Buat variabel CSS supaya bisa dipakai di Tailwind
});

// Metadata tetap sama
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ubah RootLayout untuk menggunakan variabel Poppins
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
          {children}
          <Toaster />
      </body>
    </html>
  );
}
